version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - run:
          command: curl --insecure https://raw.githubusercontent.com/sxend/dotfiles/${CIRCLE_SHA1}/install.sh | bash
workflows:
  build:
    jobs:
      - build